### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by stormckey** [TonyCrane/mkdocs-changelog-plugin#2]
MacOS 13.2.1 
python venv
Python 3.9.6
mkdocs-material                           9.1.0
mkdocs-changelog-plugin                   0.1.3

收到了下面的报错
mkdocs serve                                                                                      ─╯
Traceback (most recent call last):
  File "/Users//Desktop/web_env/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 78, in serve
    config = get_config()
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/mkdocs/config/base.py", line 363, in load_config
    errors, warnings = cfg.validate()
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/mkdocs/config/base.py", line 228, in validate
    run_failed, run_warnings = self._validate()
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/mkdocs/config/base.py", line 186, in _validate
    self[key] = config_option.validate(value)
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 147, in validate
    return self.run_validation(value)
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 939, in run_validation
    self.load_plugin_with_namespace(name, cfg)
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 975, in load_plugin_with_namespace
    return (name, self.load_plugin(name, config))
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 993, in load_plugin
    plugin_cls = self.installed_plugins[name].load()
  File "/Users//Desktop/web_env/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 208, in load
    module = import_module(match.group('module'))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mkdocs_changelog_plugin'

请问该如何解决呢

**Comment by TonyCrane** [comment]
诶奇怪，`pip show mkdocs-changelog-plugin` 看看

或者反正你下载源码然后 `pip install -e .` 这样装应该是肯定没问题的（我就是这样用的

**Comment by stormckey** [comment]
`pip show mkdocs-changelog-plugin` 出来仍然是正常的。
不过加了-e选项之后就好了。
谢谢！
